import os
import json
from dotenv import load_dotenv
from google import genai
from google.genai import types

from prompts import SYSTEM_PROMPT
from tools import (
    evaluate_documents,
    evaluate_conflict,
    evaluate_specialist,
    evaluate_client_history,
)

# Load environment variables
load_dotenv()

# Initialize Gemini client
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

# Available tools
TOOLS_LIST = [
    evaluate_documents,
    evaluate_conflict,
    evaluate_specialist,
    evaluate_client_history,
]

# Map tool names to Python functions
TOOLS_MAP = {
    "evaluate_documents": evaluate_documents,
    "evaluate_conflict": evaluate_conflict,
    "evaluate_specialist": evaluate_specialist,
    "evaluate_client_history": evaluate_client_history,
}


def run_agent(case: dict):
    """
    Runs the Unconstrained ReAct Agent.

    Args:
        case (dict): Legal case information.

    Returns:
        dict: Final JSON decision generated by Gemini.
    """

    # Create chat session
    chat = client.chats.create(
        model="gemini-2.5-flash",
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            tools=TOOLS_LIST,
            temperature=0.2,
        ),
    )

    # Send the case to Gemini
    response = chat.send_message(
        json.dumps(case, indent=2)
    )

    # -------------------- ReAct Loop --------------------
    while True:

        function_called = False

        for part in response.candidates[0].content.parts:

            if hasattr(part, "function_call") and part.function_call:

                function_called = True
                tool_name = part.function_call.name

                # Safety check
                if tool_name not in TOOLS_MAP:
                    raise ValueError(f"Unknown tool requested: {tool_name}")

                # Execute requested tool
                tool_function = TOOLS_MAP[tool_name]
                tool_result = tool_function(case)

                # Return tool result to Gemini
                response = chat.send_message(
                    types.Part.from_function_response(
                        name=tool_name,
                        response={"result": tool_result},
                    )
                )

                break

        # Gemini has finished reasoning
        if not function_called:
            break

    # -------------------- Parse Final JSON --------------------
    text = response.text.strip()

    if text.startswith("```json"):
        text = text.removeprefix("```json").removesuffix("```").strip()

    elif text.startswith("```"):
        text = text.removeprefix("```").removesuffix("```").strip()

    try:
        return json.loads(text)

    except json.JSONDecodeError:
        raise ValueError(
            f"Gemini did not return valid JSON.\n\nResponse:\n{text}"
        )
