import os
import json
from dotenv import load_dotenv
from groq import Groq

from prompts import SYSTEM_PROMPT
from shared.tools import (
    evaluate_documents,
    evaluate_conflict,
    evaluate_specialist,
    evaluate_client_history,
)

# Load environment variables
load_dotenv()

# Initialize Groq client
client = Groq(
    api_key=os.getenv("GROQ_API_KEY"),
    timeout=60.0,
)
MODEL_NAME = "llama-3.3-70b-versatile"

# Map tool names to Python functions
TOOLS_MAP = {
    "evaluate_documents": evaluate_documents,
    "evaluate_conflict": evaluate_conflict,
    "evaluate_specialist": evaluate_specialist,
    "evaluate_client_history": evaluate_client_history,
}

# Tool schemas (OpenAI-style, required by Groq)
# No parameters needed from the model itself — the case dict
# is injected locally in Python when the tool is executed.
TOOLS_SCHEMA = [
    {
        "type": "function",
        "function": {
            "name": "evaluate_documents",
            "description": "Check document status and filing deadline for the case.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "evaluate_conflict",
            "description": "Check conflict of interest status and evidence strength for the case.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "evaluate_specialist",
            "description": "Check specialist availability and urgency for the case.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
    {
        "type": "function",
        "function": {
            "name": "evaluate_client_history",
            "description": "Check client history and document archive availability.",
            "parameters": {"type": "object", "properties": {}, "required": []},
        },
    },
]


def run_agent(case: dict):
    """
    Runs the Unconstrained ReAct Agent using Groq.

    Args:
        case (dict): Legal case information.

    Returns:
        dict: Final JSON decision generated by the model.
    """

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": json.dumps(case, indent=2)},
    ]

    # -------------------- ReAct Loop --------------------
    while True:

        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=messages,
            tools=TOOLS_SCHEMA,
            tool_choice="auto",
            temperature=0.2,
        )

        message = response.choices[0].message

        # Add the assistant's message (with any tool_calls) to history
        messages.append(message)

        if message.tool_calls:
            for tool_call in message.tool_calls:
                tool_name = tool_call.function.name

                # Safety check
                if tool_name not in TOOLS_MAP:
                    raise ValueError(f"Unknown tool requested: {tool_name}")

                # Execute requested tool (always with the full case dict)
                tool_function = TOOLS_MAP[tool_name]
                tool_result = tool_function(case)

                # Return tool result to the model
                messages.append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "name": tool_name,
                    "content": json.dumps(tool_result),
                })

            # Loop again so the model can keep reasoning
            continue

        # No more tool calls -> model has finished reasoning
        break

    # -------------------- Parse Final JSON --------------------
    text = message.content.strip()

    if text.startswith("```json"):
        text = text.removeprefix("```json").removesuffix("```").strip()

    elif text.startswith("```"):
        text = text.removeprefix("```").removesuffix("```").strip()

    try:
        return json.loads(text)

    except json.JSONDecodeError:
        raise ValueError(
            f"Model did not return valid JSON.\n\nResponse:\n{text}"
        )
